Coldstart changes & fixes
- Change driver/coldstart to use /local/coldstart working dir
- coldstart start_nodeos.sh, config.ini, genesis.json files are now generated to the working dir
- improve coldstart nodeos statup error logging
- fix start/stop/clear nodes exit 0 if local/ working dir not present (means nothing to do, not error)

diff --git a/drivers/coldstart/clear b/drivers/coldstart/clear
--- a/drivers/coldstart/clear
+++ b/drivers/coldstart/clear
@@ -1,15 +1,23 @@
 #!/bin/bash
 
-# make sure the current working dir is where this script is
+# go to driver's dir to call stop
 cd "$(dirname "$0")"
 
 # stop the node if it isn't already stopped
-
 stop
+
+# now make sure the current working dir is the driver's working dir
+# at ../../local/coldstart/
+if ! cd "../../local/coldstart"; then
+  echo "coldstart clear: cannot change directory to local/coldstart; assuming no running coldstart nodeos to clear"
+  exit 0
+fi
 
 # clear node data
 
 rm -rf ./data
 rm -rf ./protocol_features
 rm -f chain.log
-
+rm -f config.ini
+rm -f genesis.json
+rm -f start_nodeos.sh
diff --git a/drivers/coldstart/stop b/drivers/coldstart/stop
--- a/drivers/coldstart/stop
+++ b/drivers/coldstart/stop
@@ -1,8 +1,12 @@
 #!/bin/bash
 
-# make sure the current working dir is where this script is
+# make sure the current working dir is the driver's working dir
+# at ../../local/coldstart/
 cd "$(dirname "$0")"
-
+if ! cd "../../local/coldstart"; then
+  echo "coldstart stop: cannot change directory to local/coldstart; assuming no coldstart nodeos to stop"
+  exit 0
+fi
 
 if [ -f "./nodeos.pid" ]; then
 pid=`cat "./nodeos.pid"`
